### ISSUE TITLE
Thumbnails support

### ISSUE THREAD

**Issue by berkes** [RISCfuture/dropbox#1]
Hello.
I have been playing with thumbnail support in Dropbox. It is not (or does not appear to be) in rdropbox. https://www.dropbox.com/developers/docs#thumbnails

The difficulty is the note:
  "The thumbnails  API call is served by the api-content subdomain unlike most calls which are served by the api subdomain. "

So, first the question: would you be interested in a pull request that adds thumbnail support at all?
And if so, how would you prefer the details to be handled? 
- Where do you think it best to add this? in Entry? API docs are a bit unclear about where this belongs. 
- How to add the alternative url-handling? Introduce a new Dropbox.content_url() method? Note that there does not appear to be a https equivalent of this content api. 

I am not very experienced ruby developer, so please don't expect a merge-and-go solution from me :)

Bèr

**Comment by berkes** [comment]
While diving deeper into your code, I see you have the content-api part sorted out already in ALTERNATE_HOSTS. Sorry for that, ignore my second bullet on that.

**Comment by berkes** [comment]
please see http://github.com/berkes/dropbox/commit/acd09a64d93484fcfd8c2b88131df9dd4c8cbeb4 for my go on this.

**Comment by RISCfuture** [comment]
I'll merge it in but it needs specs first.  Give me a little bit to write these up.

**Comment by RISCfuture** [comment]
Argh, pushed out the commit (+ specs and doc changes) and forgot to set the --author attribute.  Sorry =/

**Comment by berkes** [comment]
NP. I am happy enough about having this in. 
Thanks for all the additional documentation and specwriting. I really need to get into that too. But one thing a time (first finish the pickaxe book :P)
