### ISSUE TITLE
link method returns URL with extra /dropbox/ in path

### ISSUE THREAD

**Issue by kevindewalt** [RISCfuture/dropbox#11]
See:
http://pastie.org/1175809

Let me know if you need more info

**Comment by RISCfuture** [comment]
The '/links' API method appears to be no longer supported by Dropbox ... I can't find any mention of it on the API documentation.  Perhaps it was removed?  In any case I will leave the method in the gem for legacy purposes, but without any official documentation on the feature, I am having a hard time figuring out why the gem doesn't work in this case.
