### ISSUE TITLE
HTTP basic auth

### ISSUE THREAD

**Issue by igorw** [RISCfuture/dropbox#14]
authorize! uses a fake browser to login and authorize. Why does it go through the GUI? Wouldn't it make more sense to use the existing support for basic auth?

**Comment by RISCfuture** [comment]
Can you point me to some docs for this Basic Auth support?

**Comment by igorw** [comment]
Turns out, it's not actual basic auth, but an API to receive a token via email/password.

You make a request to /token supplying email and password parameters.

https://www.dropbox.com/developers/docs

**Comment by RISCfuture** [comment]
The authorize! method was originally written for integration testing with the OAuth API.  Supporting the token API is a completely different feature which I'll work on.
