### ISSUE TITLE
cli usage

### ISSUE THREAD

**Issue by webdev** [RISCfuture/dropbox#16]
hi there, 

it's not an issue, but how do you use dropbox gem on cli? I'm getting Dropbox::UnsuccessfulResponseError: HTTP status Net::HTTPForbidden received: http://api.dropbox.com/0/metadata/sandbox?list=true. 

I think it has to do with the fact that there is no authorization cookie right?

**Comment by RISCfuture** [comment]
OAuth is not a cookie-based authorization system.  Neither Dropbox::Session nor OAuth interact with cookies in any way.  True, the Rails example code makes use of the #serialize/#deserialize methods to store the Dropbox session into the cookie, but that's all Rails.  The #serialize/#deserialize methods just convert a Dropbox::Session into a string and vice versa.

You should be able to use the CLI, as shown in the example code in the readme file.  As I said in my response to your other post, you should make sure that your credentials are valid by testing with a different API.

**Comment by RISCfuture** [comment]
Closing.
