### ISSUE TITLE
Is the Session#link method working fine?

### ISSUE THREAD

**Issue by Dagnan** [RISCfuture/dropbox#19]
I'm trying to use the #link method, but the generated link is not working because of the current mode inserted in it. If I remove it it works.

Please note that I've just discovered your plugin today, and did not have a lot of time to work on it so maybe I miss something important.

Thanks :)

**Comment by RISCfuture** [comment]
The links API method is no longer documented in the Dropbox API reference.  I assume it has been deprecated or removed, so I can no longer support it unfortunately.

**Comment by Dagnan** [comment]
Thanks.
