### ISSUE TITLE
Can`t upload files with rails app

### ISSUE THREAD

**Issue by hoblin** [RISCfuture/dropbox#2]
When i try upload file with rails app i get the following error message:
http://pastie.org/1055520

**Comment by RISCfuture** [comment]
I'm unable to reproduce this problem in Ruby 1.8.7 and 1.9.1. Is there anything unusual about your environment that might contribute to this problem?

**Comment by hoblin** [comment]
I tested in on just created rails app with only dropbox gem configured in environment.rb
OS: Snow Leopard
Ruby: 1.8.7
RubyGems: 1.3.7
Rails: 2.3.8
All installed gems: http://pastie.org/1056615

**Comment by guilleiguaran** [comment]
Please post your enviroment.rb to know the gems used in the project

**Comment by hoblin** [comment]
only dropbox gem included

**Comment by RISCfuture** [comment]
Did you end up figuring this out?

**Comment by hoblin** [comment]
A year has passed. I don't remember =)
