### ISSUE TITLE
Cannot install anymore on projects using rspec 1

### ISSUE THREAD

**Issue by masterkain** [RISCfuture/dropbox#21]
Gemfile contains a dependency on rspec 2, but it's not grouped, so:

Bundler could not find compatible versions for gem "rspec":
  In Gemfile:
    dropbox depends on
      rspec (>= 2.0)

```
rspec (1.3.1)
```

**Comment by RISCfuture** [comment]
Version 1.2.2 fixes this by removing the rspec dependency.
