### ISSUE TITLE
Sinatra Example

### ISSUE THREAD

**Issue by stefanobernardi** [RISCfuture/dropbox#22]
I have some problems in serializing and deserializing in Sinatra. it would be awesome if you could add a small example for that.

Thanks.

**Comment by RISCfuture** [comment]
Can you give more detail about what your problems are?

**Comment by stefanobernardi** [comment]
Managed.

**Comment by stefanobernardi** [comment]
Here is the Sinatra example if you want to include it in your readme
https://github.com/stefanobernardi/sinatra-dropbox
