### ISSUE TITLE
Directory modified hashes not supported

### ISSUE THREAD

**Issue by coreyward** [RISCfuture/dropbox#24]
Per the Dropbox API:

> Use the hash parameter to metadata with the last hash you had so that you can get a shorter 
> list. What this does is give you a 304 if hash matches, and the contents again if the hash is 
> different from what we have.

Unfortunately, it doesn't appear that this gem supports that functionality. It looks like support was started, but the relevant line that hands the `:hash` option on in `Dropbox::API#metadata` is commented out:

```
#args.last[:hash] = options[:hash] if options[:hash]
```

I'm curious _why_ this is the case. I don't want to have to loop through all of the files in the directory to determine which have changed when the hash is different if I can avoid doing so. I suspect it has something to do with handling that 304 status or avoiding unexpected behavior in regards to deleted files (which apparently don't affect the hash returned in metadata calls to the Dropbox API).

**Comment by RISCfuture** [comment]
Done -- 7c16bc4ddd4f6cc1185d426fb7e70648d4fb739e (push forthcoming)
