### ISSUE TITLE
Dummy implementation

### ISSUE THREAD

**Issue by fguillen** [RISCfuture/dropbox#3]
Hi people.

For my own proposes I have started to develop a dummy dropbox implementation so I can use it on my tests.

You can check it here:
- http://github.com/fguillen/DummyDropbox

Just wondering if this could be helpful for some one, and if you want to public the idea on some official place so a more complete implementation could be done.

Regards

f.

**Comment by RISCfuture** [comment]
Thanks, I'll include it in the README.

**Comment by fguillen** [comment]
Great ;), thanks to you for your work.
