### ISSUE TITLE
Minor error in README.rdoc example

### ISSUE THREAD

**Issue by mike15** [RISCfuture/dropbox#30]
In the tutorial by example, the code listed:
session.upload('testfile.txt')
uploaded_file = session.file('testfile.txt', '/')

Being new to this gem, I think the two command parameters are swapped and should be:
session.upload('testfile.txt', '/')
uploaded_file = session.file('/testfile.txt')

Thanks!

**Comment by RISCfuture** [comment]
Fixed.
