### ISSUE TITLE
Why is the length of the path limited to 255 characters?

### ISSUE THREAD

**Issue by ghost** [RISCfuture/dropbox#31]
Hello,

I've just a little question, when I was going through the code I noted the method self.check_path. It is used multiple times, but I can't figure out why. 
In Dropbox the length  of a name is limited to 255 characters, but not the path. And I successfully created 
"ttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttt /
tttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttt /
tttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttt"
in Dropbox.
But when I use the Dropbox API  to get the metadata of this folder I get the error  "Dropbox paths are limited to 256 characters in length".
Is this intentional?

Groetjes

Nele

**Comment by RISCfuture** [comment]
Probably a mistake on my part.  Fixed.
