### ISSUE TITLE
Does Session.authorize! still work?

### ISSUE THREAD

**Issue by kimptoc** [RISCfuture/dropbox#38]
Hi,

I am trying to use the user/password route via the authorize! method but it does not seem to be getting past the login - get redirected back, even though I can see the correct details being sent (using Charles).

I guess its not the Dropbox preferred route these days :(

Thanks,
Chris

**Comment by RISCfuture** [comment]
To be fair, it was never a Dropbox preferred route.  Dropbox claimns that you never store the user's login and password.  The `authorize!` method is a hack, using screen-scraping, that will break any time Dropbox changes the layout of their login page.  I don't really recommend it's use in any production system.

**Comment by kimptoc** [comment]
Thanks and agreed - just thought I'd try for a command line play with the gem.

**Comment by RISCfuture** [comment]
Solved by removing the `authorize!` method :)

**Comment by kimptoc** [comment]
Great, thanks.
