### ISSUE TITLE
authorize! not working ?

### ISSUE THREAD

**Issue by ouranos** [RISCfuture/dropbox#39]
Hi,

`Session#authorize!` doesn't seem to work.

I had a look at it and it appears that `login_form.submit` is not working: the page returned is another login page and not the authorization page.

**Comment by charleschen** [comment]
i was getting the same behavior.  But i read an older issue here:

https://github.com/RISCfuture/dropbox/issues/38

I'm guessing dropbox changed the layout of the login page.  It's not a recommended way of login in anyways

**Comment by ouranos** [comment]
Thanks. I should have searched a bit more before but didn't see any opened issues.

I'm getting this issue with the backup gem which is using authorize! (https://github.com/meskyanichi/backup/blob/develop/lib/backup/storage/dropbox.rb).
I'll lodge a ticket there.

It might be a good idea to recommend against using it in the doc.

**Comment by RISCfuture** [comment]
Solved by removing the `authorize!` method :)
