### ISSUE TITLE
DropboxController::Filebox

### ISSUE THREAD

**Issue by pradeepbicc** [RISCfuture/dropbox#41]
I'm trying to add dropbox in my add. 
My guide: http://hafizbadrie.wordpress.com/2011/08/07/ruby-on-rails-connect-to-dropbox-authorization-and-upload/

Baam!! Erro!r!
NameError in DropboxesController#index

uninitialized constant DropboxController::Filebox

how to get over this!!
thanks in advance

**Comment by RISCfuture** [comment]
`Filebox` is not a part of the Dropbox gem.  I'm not sure what library is responsible for the `Filebox` class, sorry.
