### ISSUE TITLE
Dropbox API v1

### ISSUE THREAD

**Issue by tvongaza** [RISCfuture/dropbox#43]
Any plans to add support for the new methods in the v1 API?

https://www.dropbox.com/developers_beta

**Comment by RISCfuture** [comment]
I really would love to, but I've moved on from the company that actually used the gem to a company that doesn't use Dropbox integration, so unfortunately it's hard to find the time.  I'm accepting pull requests, or hopefully sometime I will have a few hours to write and test the code.
